# This file is a dictionary used by the [link-dependencies](https://github.com/newrelic/release-toolkit/tree/main/link-dependencies) action.

dictionary:
  newrelic/nri-apache: "https://github.com/newrelic/nri-apache/releases/tag/{{.To}}"
  newrelic/nri-cassandra: "https://github.com/newrelic/nri-cassandra/releases/tag/{{.To}}"
  newrelic/nri-consul: "https://github.com/newrelic/nri-consul/releases/tag/{{.To}}"
  newrelic/nri-couchbase: "https://github.com/newrelic/nri-couchbase/releases/tag/{{.To}}"
  newrelic/nri-elasticsearch: "https://github.com/newrelic/nri-elasticsearch/releases/tag/{{.To}}"
  newrelic/nri-f5: "https://github.com/newrelic/nri-f5/releases/tag/{{.To}}"
  newrelic/nri-haproxy: "https://github.com/newrelic/nri-haproxy/releases/tag/{{.To}}"
  newrelic/nri-jmx: "https://github.com/newrelic/nri-jmx/releases/tag/{{.To}}"
  newrelic/nri-kafka: "https://github.com/newrelic/nri-kafka/releases/tag/{{.To}}"
  newrelic/nri-memcached: "https://github.com/newrelic/nri-memcached/releases/tag/{{.To}}"
  newrelic/nri-mongodb: "https://github.com/newrelic/nri-mongodb/releases/tag/{{.To}}"
  newrelic/nri-mysql: "https://github.com/newrelic/nri-mysql/releases/tag/{{.To}}"
  newrelic/nri-nagios: "https://github.com/newrelic/nri-nagios/releases/tag/{{.To}}"
  newrelic/nri-nginx: "https://github.com/newrelic/nri-nginx/releases/tag/{{.To}}"
  newrelic/nri-postgresql: "https://github.com/newrelic/nri-postgresql/releases/tag/{{.To}}"
  newrelic/nri-rabbitmq: "https://github.com/newrelic/nri-rabbitmq/releases/tag/{{.To}}"
  newrelic/nri-redis: "https://github.com/newrelic/nri-redis/releases/tag/{{.To}}"
  newrelic/nrjmx: "https://github.com/newrelic/nrjmx/releases/tag/{{.To}}"
  newrelic/nri-discovery-kubernetes: "https://github.com/newrelic/nri-discovery-kubernetes/releases/tag/{{.To}}"
  newrelic/nri-mssql: "https://github.com/newrelic/nri-mssql/releases/tag/{{.To}}"
  newrelic/infrastructure: "https://github.com/newrelic/infrastructure-agent/releases/tag/{{.To}}"
