# escape=`

ARG agent_version=latest
ARG base_image_name=newrelic/infrastructure
ARG base_image=${base_image_name}:${agent_version}

FROM ${base_image}

ARG out_dir=out-windows
ARG TARGETARCH=amd64

# Copy integrations from the out-windows directory
COPY ${out_dir}/${TARGETARCH} /
