name: Trigger prerelease creation

# This workflow triggers a prerelease creation with changelog and the release notes created by the release toolkit.
# This workflow should be triggered merely from the default branch.
# If you wish to be 100% free creating a prerelease, just create it manually.

on:
  workflow_dispatch:
  schedule:
    - cron: "30 10 * * 3"

jobs:
  prerelease:
    name: Create prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Check is triggered for default branch
        run: |
          if [ ${GITHUB_REF_NAME} != ${{ github.event.repository.default_branch }} ] || [ ${GITHUB_REF_TYPE} != "branch" ];then
            echo This workflow should only be triggered for the '${{ github.event.repository.default_branch }}' branch
            exit 1
          fi
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}
          token: "${{ secrets.COREINT_BOT_TOKEN }}"
      - uses: newrelic/release-toolkit/contrib/ohi-release-notes@v1
        id: release-data
      - name: Configure Git
        if: ${{ steps.release-data.outputs.skip-release != 'true' }}
        run: |
          git config user.name newrelic-coreint-team
          git config user.email coreint-dev@newrelic.com
      - name: Commit updated changelog
        if: ${{ steps.release-data.outputs.skip-release != 'true' }}
        run: |
          git add CHANGELOG.md
          git commit -m "Update changelog with changes from ${{ steps.release-data.outputs.next-version }}"
          git push -u origin ${{ github.event.repository.default_branch }}
      - name: Create prerelease
        if: ${{ steps.release-data.outputs.skip-release != 'true' }}
        env:
          GH_TOKEN: "${{ secrets.COREINT_BOT_TOKEN }}"
        run: |
          gh release create ${{ steps.release-data.outputs.next-version }} --target $(git rev-parse HEAD) --notes-file CHANGELOG.partial.md --prerelease
